// Package nftgen renders the complete nftables transaction file that
// nft-blocklist applies with `nft -f`. The whole file executes as a single
// kernel transaction: on any error nothing changes, so the firewall can
// never be left partially updated.
package nftgen

import (
	"fmt"
	"net/netip"
	"strings"

	"github.com/dannysheehan/nft-blocklist/internal/config"
	"github.com/dannysheehan/nft-blocklist/internal/ipmath"
)

// Sets managed inside the table. The dynamic sets belong to fail2ban (or
// any other reactive tool): they are declared so rules can reference them,
// but a feed update never flushes or writes elements into them.
const (
	SetAllow4   = "allow4"
	SetAllow6   = "allow6"
	SetStatic4  = "static4"
	SetStatic6  = "static6"
	SetDynamic4 = "dynamic4"
	SetDynamic6 = "dynamic6"
)

// elementsPerLine keeps generated `add element` lines reviewable and under
// nft's line-length comfort zone.
const elementsPerLine = 200

// Input is everything the renderer needs. GeneratedBy/GeneratedAt are
// free-form header text (kept injectable so golden tests are stable).
type Input struct {
	Cfg         config.Config
	Static      ipmath.Result // merged blocklist minus allowlist
	Allow       ipmath.Result // merged allowlist
	GeneratedBy string
	GeneratedAt string
}

// Render produces the full .nft transaction file contents.
func Render(in Input) string {
	var b strings.Builder
	t := in.Cfg.NFT.Table
	chain := in.Cfg.NFT.Chain
	pol := in.Cfg.Policy

	fmt.Fprintf(&b, "#!/usr/sbin/nft -f\n")
	fmt.Fprintf(&b, "# Generated by %s at %s -- DO NOT EDIT.\n", in.GeneratedBy, in.GeneratedAt)
	fmt.Fprintf(&b, "# Applied atomically: this file either fully applies or not at all.\n\n")

	// Declarations are idempotent (`add` succeeds when the object already
	// exists), so first runs and update runs share one code path.
	fmt.Fprintf(&b, "add table inet %s\n", t)
	fmt.Fprintf(&b, "add set inet %s %s { type ipv4_addr; flags interval; auto-merge; }\n", t, SetAllow4)
	fmt.Fprintf(&b, "add set inet %s %s { type ipv6_addr; flags interval; auto-merge; }\n", t, SetAllow6)
	fmt.Fprintf(&b, "add set inet %s %s { type ipv4_addr; flags interval; auto-merge; }\n", t, SetStatic4)
	fmt.Fprintf(&b, "add set inet %s %s { type ipv6_addr; flags interval; auto-merge; }\n", t, SetStatic6)
	fmt.Fprintf(&b, "add set inet %s %s { type ipv4_addr; flags timeout; }\n", t, SetDynamic4)
	fmt.Fprintf(&b, "add set inet %s %s { type ipv6_addr; flags timeout; }\n", t, SetDynamic6)
	fmt.Fprintf(&b, "add chain inet %s %s { type filter hook input priority %d ; policy accept ; }\n",
		t, chain, in.Cfg.NFT.Priority)
	b.WriteString("\n")

	// Flush our managed state. The dynamic sets are deliberately absent.
	fmt.Fprintf(&b, "flush chain inet %s %s\n", t, chain)
	for _, s := range []string{SetAllow4, SetAllow6, SetStatic4, SetStatic6} {
		fmt.Fprintf(&b, "flush set inet %s %s\n", t, s)
	}
	b.WriteString("\n")

	// Rules. Allowlist wins first; then rate-limited audit logging for the
	// configured service ports; then the block action.
	fmt.Fprintf(&b, "add rule inet %s %s ip saddr @%s accept\n", t, chain, SetAllow4)
	fmt.Fprintf(&b, "add rule inet %s %s ip6 saddr @%s accept\n", t, chain, SetAllow6)

	if len(pol.LogTCPPorts) > 0 {
		ports := joinPorts(pol.LogTCPPorts)
		fmt.Fprintf(&b, "add rule inet %s %s ip saddr @%s tcp dport { %s } ct state new limit rate %s counter log prefix \"%s\"\n",
			t, chain, SetStatic4, ports, pol.LogRate, pol.LogPrefix)
		fmt.Fprintf(&b, "add rule inet %s %s ip6 saddr @%s tcp dport { %s } ct state new limit rate %s counter log prefix \"%s\"\n",
			t, chain, SetStatic6, ports, pol.LogRate, pol.LogPrefix)
	}
	if len(pol.LogUDPPorts) > 0 {
		ports := joinPorts(pol.LogUDPPorts)
		fmt.Fprintf(&b, "add rule inet %s %s ip saddr @%s udp dport { %s } limit rate %s counter log prefix \"%s\"\n",
			t, chain, SetStatic4, ports, pol.LogRate, pol.LogPrefix)
		fmt.Fprintf(&b, "add rule inet %s %s ip6 saddr @%s udp dport { %s } limit rate %s counter log prefix \"%s\"\n",
			t, chain, SetStatic6, ports, pol.LogRate, pol.LogPrefix)
	}

	action := "drop"
	if pol.Action == config.ActionReject {
		action = "reject"
	}
	fmt.Fprintf(&b, "add rule inet %s %s ip saddr @%s counter %s\n", t, chain, SetStatic4, action)
	fmt.Fprintf(&b, "add rule inet %s %s ip6 saddr @%s counter %s\n", t, chain, SetStatic6, action)
	fmt.Fprintf(&b, "add rule inet %s %s ip saddr @%s counter %s\n", t, chain, SetDynamic4, action)
	fmt.Fprintf(&b, "add rule inet %s %s ip6 saddr @%s counter %s\n", t, chain, SetDynamic6, action)
	b.WriteString("\n")

	writeElements(&b, t, SetAllow4, in.Allow.V4)
	writeElements(&b, t, SetAllow6, in.Allow.V6)
	writeElements(&b, t, SetStatic4, in.Static.V4)
	writeElements(&b, t, SetStatic6, in.Static.V6)

	return b.String()
}

func writeElements(b *strings.Builder, table, set string, prefixes []netip.Prefix) {
	for start := 0; start < len(prefixes); start += elementsPerLine {
		end := min(start+elementsPerLine, len(prefixes))
		items := make([]string, 0, end-start)
		for _, p := range prefixes[start:end] {
			items = append(items, prefixString(p))
		}
		fmt.Fprintf(b, "add element inet %s %s { %s }\n", table, set, strings.Join(items, ", "))
	}
}

// prefixString renders host prefixes as bare addresses (nft displays them
// that way; emitting the same form keeps status diffs clean).
func prefixString(p netip.Prefix) string {
	if p.IsSingleIP() {
		return p.Addr().String()
	}
	return p.String()
}

func joinPorts(ports []int) string {
	ss := make([]string, len(ports))
	for i, p := range ports {
		ss[i] = fmt.Sprint(p)
	}
	return strings.Join(ss, ", ")
}
